//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.Service {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceUser.TypeMsg", Namespace="http://schemas.datacontract.org/2004/07/ChatService")]
    public enum ServiceUserTypeMsg : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Connect = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disconnect = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IServiceChat", CallbackContract=typeof(ChatClient.Service.IServiceChatCallback))]
    public interface IServiceChat {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChat/SendMsg")]
        void SendMsg(string username, string msg, ChatClient.Service.ServiceUserTypeMsg typeMsg, int userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChat/SendMsg")]
        System.Threading.Tasks.Task SendMsgAsync(string username, string msg, ChatClient.Service.ServiceUserTypeMsg typeMsg, int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChat/MsgCallback")]
        void MsgCallback(string username, string msg, ChatClient.Service.ServiceUserTypeMsg typeMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChatChannel : ChatClient.Service.IServiceChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceChatClient : System.ServiceModel.DuplexClientBase<ChatClient.Service.IServiceChat>, ChatClient.Service.IServiceChat {
        
        public ServiceChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMsg(string username, string msg, ChatClient.Service.ServiceUserTypeMsg typeMsg, int userId) {
            base.Channel.SendMsg(username, msg, typeMsg, userId);
        }
        
        public System.Threading.Tasks.Task SendMsgAsync(string username, string msg, ChatClient.Service.ServiceUserTypeMsg typeMsg, int userId) {
            return base.Channel.SendMsgAsync(username, msg, typeMsg, userId);
        }
    }
}
